var specMap = {
    "motion_movesteps": ["forward:", [["input", "STEPS"]]],
    "motion_turnright": ["turnRight:", [["input", "DEGREES"]]],
    "motion_turnleft": ["turnLeft:", [["input", "DEGREES"]]],
    "motion_pointindirection": ["heading:", [["input", "DIRECTION"]]],
    "motion_pointtowards": ["pointTowards:", [["input", "TOWARDS"]]],
    "motion_gotoxy": ["gotoX:y:", [["input", "X"], ["input", "Y"]]],
    "motion_goto": ["gotoSpriteOrMouse:", [["input", "TO"]]],
    "motion_goto_menu": ["", [["field", "TO"]]],
    "motion_glidesecstoxy": ["glideSecs:toX:y:elapsed:from:", [["input", "SECS"], ["input", "X"], ["input", "Y"]]],
    "motion_changexby": ["changeXposBy:", [["input", "DX"]]],
    "motion_setx": ["xpos:", [["input", "X"]]],
    "motion_changeyby": ["changeYposBy:", [["input", "DY"]]],
    "motion_sety": ["ypos:", [["input", "Y"]]],
    "motion_ifonedgebounce": ["bounceOffEdge", []],
    "motion_setrotationstyle": ["setRotationStyle", [["field", "STYLE"]]],
    "motion_glideto": ["motion_glideto"],
    "motion_xposition": ["xpos", []],
    "motion_yposition": ["ypos", []],
    "motion_direction": ["heading", []],
    "motion_scroll_right": ["scrollRight", [["input", "DISTANCE"]]],
    "motion_scroll_up": ["scrollUp", [["input", "DISTANCE"]]],
    "motion_align_scene": ["scrollAlign", [["field", "ALIGNMENT"]]],
    "motion_xscroll": ["xScroll", []],
    "motion_yscroll": ["yScroll", []],

    "looks_sayforsecs": ["say:duration:elapsed:from:", [["input", "MESSAGE"], ["input", "SECS"]]],
    "looks_say": ["say:", [["input", "MESSAGE"]]],
    "looks_thinkforsecs": ["think:duration:elapsed:from:", [["input", "MESSAGE"], ["input", "SECS"]]],
    "looks_think": ["think:", [["input", "MESSAGE"]]],
    "looks_show": ["show", []],
    "looks_hide": ["hide", []],
    "looks_hideallsprites": ["hideAll", []],
    "looks_switchcostumeto": ["lookLike:", [["input", "COSTUME"]]],
    "looks_nextcostume": ["nextCostume", []],
    "looks_switchbackdropto": ["startScene", [["input", "BACKDROP"]]],
    "looks_changeeffectby": ["changeGraphicEffect:by:", [["field", "EFFECT"], ["input", "CHANGE"]]],
    "looks_seteffectto": ["setGraphicEffect:to:", [["field", "EFFECT"], ["input", "VALUE"]]],
    "looks_cleargraphiceffects": ["filterReset", []],
    "looks_changesizeby": ["changeSizeBy:", [["input", "CHANGE"]]],
    "looks_setsizeto": ["setSizeTo:", [["input", "SIZE"]]],
    "looks_changestretchby": ["changeStretchBy:", [["input", "CHANGE"]]],
    "looks_setstretchto": ["setStretchTo:", [["input", "STRETCH"]]],
    "looks_gotofrontback": ["comeToFront", []],
    "looks_goforwardbackwardlayers": ["goBackByLayers:", [["input", "NUM"]]],
    "looks_costumenumbername": ["costumeName", []],
    "looks_backdropnumbername": ["backgroundIndex", []],
    "looks_size": ["scale", []],
    "looks_switchbackdroptoandwait": ["startSceneAndWait", [["input", "BACKDROP"]]],
    "looks_nextbackdrop": ["nextScene", []],

    "sound_play": ["playSound:", [["input", "SOUND_MENU"]]],
    "sound_playuntildone": ["doPlaySoundAndWait", [["input", "SOUND_MENU"]]],
    "sound_stopallsounds": ["stopAllSounds", []],
    "sound_changevolumeby": ["changeVolumeBy:", [["input", "VOLUME"]]],
    "sound_setvolumeto": ["setVolumeTo:", [["input", "VOLUME"]]],
    "sound_volume": ["volume", []],

    "music_changeTempo": ["changeTempoBy:", [["input", "TEMPO"]]],
    "music_playDrumForBeats": ["playDrum", [["input", "DRUM"], ["input", "BEATS"]]],
    "music_midiPlayDrumForBeats": ["drum:duration:elapsed:from:", [["input", "DRUM"], ["input", "BEATS"]]],
    "music_restForBeats": ["rest:elapsed:from:", [["input", "BEATS"]]],
    "music_playNoteForBeats": ["noteOn:duration:elapsed:from:", [["input", "NOTE"], ["input", "BEATS"]]],
    "music_setInstrument": ["instrument:", [["input", "INSTRUMENT"]]],
    "music_midiSetInstrument": ["midiInstrument:", [["input", "INSTRUMENT"]]],
    "music_setTempo": ["setTempoTo:", [["input", "TEMPO"]]],
    "music_getTempo": ["tempo", []], "pen_clear": ["clearPenTrails", []],

    "pen_stamp": ["stampCostume", []],
    "pen_penDown": ["putPenDown", []],
    "pen_penUp": ["putPenUp", []],
    "pen_setPenColorToColor": ["penColor:", [["input", "COLOR"]]],
    "pen_changePenHueBy": ["changePenHueBy:", [["input", "HUE"]]],
    "pen_setPenHueToNumber": ["setPenHueTo:", [["input", "HUE"]]],
    "pen_changePenShadeBy": ["changePenShadeBy:", [["input", "SHADE"]]],
    "pen_setPenShadeToNumber": ["setPenShadeTo:", [["input", "SHADE"]]],
    "pen_changePenSizeBy": ["changePenSizeBy:", [["input", "SIZE"]]],
    "pen_setPenSizeTo": ["penSize:", [["input", "SIZE"]]],

    "event_whenflagclicked": ["whenGreenFlag", []],
    "event_whenkeypressed": ["whenKeyPressed", [["field", "KEY_OPTION"]]],
    "event_whenthisspriteclicked": ["whenClicked", []],
    "event_whenbackdropswitchesto": ["whenSceneStarts", [["field", "BACKDROP"]]],
    "event_whenbroadcastreceived": ["whenIReceive", [["field", "BROADCAST_OPTION"]]],
    "event_broadcast": ["broadcast:", [["input", "BROADCAST_INPUT"]]],
    "event_broadcastandwait": ["doBroadcastAndWait", [["input", "BROADCAST_INPUT"]]],
    "event_whengreaterthan": ["whenSensorGreaterThan", [["field", "WHENGREATERTHANMENU"], ["input", "VALUE"]]],

    "control_wait": ["wait:elapsed:from:", [["input", "DURATION"]]],
    "control_repeat": ["doRepeat", [["input", "TIMES"], ["input", "SUBSTACK"]]],
    "control_forever": ["doForever", [["input", "SUBSTACK"]]],
    "control_if": ["doIf", [["input", "CONDITION"], ["input", "SUBSTACK"]]],
    "control_if_else": ["doIfElse", [["input", "CONDITION"], ["input", "SUBSTACK"], ["input", "SUBSTACK2"]]],
    "control_wait_until": ["doWaitUntil", [["input", "CONDITION"]]],
    "control_repeat_until": ["doUntil", [["input", "CONDITION"], ["input", "SUBSTACK"]]],
    "control_while": ["doWhile", [["input", "CONDITION"], ["input", "SUBSTACK"]]],
    "control_for_each": ["doForLoop", [["field", "VARIABLE"], ["input", "VALUE"], ["input", "SUBSTACK"]]],
    "control_stop": ["stopScripts", [["field", "STOP_OPTION"]]],
    "control_start_as_clone": ["whenCloned", []],
    "control_create_clone_of": ["createCloneOf", [["input", "CLONE_OPTION"]]],
    "control_delete_this_clone": ["deleteClone", []],
    "control_get_counter": ["COUNT", []],
    "control_incr_counter": ["INCR_COUNT", []],
    "control_clear_counter": ["CLR_COUNT", []],
    "control_all_at_once": ["warpSpeed", [["input", "SUBSTACK"]]],

    "sensing_touchingobject": ["touching:", [["input", "TOUCHINGOBJECTMENU"]]],
    "sensing_touchingcolor": ["touchingColor:", [["input", "COLOR"]]],
    "sensing_coloristouchingcolor": ["color:sees:", [["input", "COLOR"], ["input", "COLOR2"]]],
    "sensing_distanceto": ["distanceTo:", [["input", "DISTANCETOMENU"]]],
    "sensing_askandwait": ["doAsk", [["input", "QUESTION"]]],
    "sensing_answer": ["answer", []],
    "sensing_keypressed": ["keyPressed:", [["input", "KEY_OPTION"]]],
    "sensing_mousedown": ["mousePressed", []],
    "sensing_mousex": ["mouseX", []],
    "sensing_mousey": ["mouseY", []],
    "sensing_loudness": ["soundLevel", []],
    "sensing_loud": ["isLoud", []],
    "sensing_timer": ["timer", []],
    "sensing_resettimer": ["timerReset", []],
    "sensing_of": ["getAttribute:of:", [["field", "PROPERTY"], ["input", "OBJECT"]]],
    "sensing_current": ["timeAndDate", [["field", "CURRENTMENU"]]],
    "sensing_dayssince2000": ["timestamp", []],
    "sensing_username": ["getUserName", []],
    "sensing_userid": ["getUserId", []],    

    "videoSensing_videoToggle": ["setVideoState", [["input", "VIDEO_STATE"]]],
    "videoSensing_setVideoTransparency": ["setVideoTransparency", [["input", "TRANSPARENCY"]]],
    "videoSensing_videoOn": ["senseVideoMotion", [["input", "ATTRIBUTE"], ["input", "SUBJECT"]]],

    "operator_add": ["+", [["input", "NUM1"], ["input", "NUM2"]]],
    "operator_subtract": ["-", [["input", "NUM1"], ["input", "NUM2"]]],
    "operator_multiply": ["*", [["input", "NUM1"], ["input", "NUM2"]]],
    "operator_divide": ["/", [["input", "NUM1"], ["input", "NUM2"]]],
    "operator_random": ["randomFrom:to:", [["input", "FROM"], ["input", "TO"]]],
    "operator_lt": ["<", [["input", "OPERAND1"], ["input", "OPERAND2"]]],
    "operator_equals": ["=", [["input", "OPERAND1"], ["input", "OPERAND2"]]],
    "operator_gt": [">", [["input", "OPERAND1"], ["input", "OPERAND2"]]],
    "operator_and": ["&", [["input", "OPERAND1"], ["input", "OPERAND2"]]],
    "operator_or": ["|", [["input", "OPERAND1"], ["input", "OPERAND2"]]],
    "operator_not": ["not", [["input", "OPERAND"]]],
    "operator_join": ["concatenate:with:", [["input", "STRING1"], ["input", "STRING2"]]],
    "operator_letter_of": ["letter:of:", [["input", "LETTER"], ["input", "STRING"]]],
    "operator_length": ["stringLength:", [["input", "STRING"]]],
    "operator_mod": ["%", [["input", "NUM1"], ["input", "NUM2"]]],
    "operator_round": ["rounded", [["input", "NUM"]]],
    "operator_mathop": ["computeFunction:of:", [["field", "OPERATOR"], ["input", "NUM"]]],

    "data_variable": ["getVar:", [["field", "VARIABLE"]]],
    "data_setvariableto": ["setVar:to:", [["field", "VARIABLE"], ["input", "VALUE"]]],
    "data_changevariableby": ["changeVar:by:", [["field", "VARIABLE"], ["input", "VALUE"]]],
    "data_showvariable": ["showVariable:", [["field", "VARIABLE"]]],
    "data_hidevariable": ["hideVariable:", [["field", "VARIABLE"]]],
    "data_listcontents": ["contentsOfList:", [["field", "LIST"]]],
    "data_addtolist": ["append:toList:", [["input", "ITEM"], ["field", "LIST"]]],
    "data_deleteoflist": ["deleteLine:ofList:", [["input", "INDEX"], ["field", "LIST"]]],
    "data_insertatlist": ["insert:at:ofList:", [["input", "ITEM"], ["input", "INDEX"], ["field", "LIST"]]],
    "data_replaceitemoflist": ["setLine:ofList:to:", [["input", "INDEX"], ["field", "LIST"], ["input", "ITEM"]]],
    "data_itemoflist": ["getLine:ofList:", [["input", "INDEX"], ["field", "LIST"]]],
    "data_lengthoflist": ["lineCountOfList:", [["field", "LIST"]]],
    "data_listcontainsitem": ["list:contains:", [["field", "LIST"], ["input", "ITEM"]]],
    "data_showlist": ["showList:", [["field", "LIST"]]],
    "data_hidelist": ["hideList:", [["field", "LIST"]]],

    "procedures_definition": ["procDef", []],

    "argument_reporter_string_number": ["getParam", [["field", "VALUE"]]]
};

module.exports = { specMap };